version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      # - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
